### ISSUE TITLE
Getting all the textual description (observations)

### ISSUE THREAD

**Issue by ktr0921** [microsoft/jericho#39]
I'm wondering if there is any way I can extract all the textual description (observations) inside all the game.

**Comment by mhauskn** [comment]
There's a nearly unlimited number of textual observations for any game as the text of the observation can change based on what objects are in the room. So it's hard to extract "all" the observations from a game. A couple approximations you might consider:

1. If you are interested mainly in the games in the Jericho suite, run the walkthrough for the game and record the observations encountered. Walkthroughs aren't guaranteed to be exhaustive, but they will likely get pretty good coverage of the possible places you can visit in a game. See example at: https://jericho-py.readthedocs.io/en/latest/tutorial_quick.html#walkthroughs
2. If you are interested in a large sampling of observations from games in and beyond the Jericho suite, consider using ClubFloyd Dataset which can be found at https://github.com/princeton-nlp/calm-textgame.

**Comment by ktr0921** [comment]
Cheers.

**Comment by altsoph** [comment]
@ktr0921
For my research I tried to get all the descriptions (not only room descriptions but detailed item descriptions as well), so I used a combination of 3 approaches:
* for the games with full support by the Jericho suite I enumerated rooms by running the walkthrough and calling env.get_player_location() first, plus I stored a walkthrough prefix to be able to restart the game and replay the prefix to get into the room, then I tried to 'examine' each word in the room's description, finally, I cleaned out dummy messages.
* next, I collected 24 more games with working solutions, here I used a room's title (the first line of observation) instead of get_player_location() to identify the room, the rest was the same.
* finally, I used just random walks to generate pseudo-solutions for the rest of the games; the results had a very low recall but there are tons of such games so even this simple approach gave me a lot of data.

@mhauskn 
BTW, I can share 24 games with solutions currently unsupported by Jericho, if you are interested :)

**Comment by mhauskn** [comment]
@altsoph, sure, I'd be interested to learn more about these 24 games.

**Comment by altsoph** [comment]
> @altsoph, sure, I'd be interested to learn more about these 24 games.

Just sent you an email

**Comment by ktr0921** [comment]
@altsoph
Thank you. I will try them and see how it goes, and will let you know if I find another way.
